/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RetroRouteImport } from './routes/retro'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ListsIdRouteImport } from './routes/lists.$id'
import { Route as GamesIdRouteImport } from './routes/games.$id'
import { Route as FranchiseSlugRouteImport } from './routes/franchise.$slug'
import { Route as DecadeSlugRouteImport } from './routes/decade.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthSteamReturnRouteImport } from './routes/auth.steam.return'
import { Route as AuthSteamLoginRouteImport } from './routes/auth.steam.login'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RetroRoute = RetroRouteImport.update({
  id: '/retro',
  path: '/retro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseSlugRoute = FranchiseSlugRouteImport.update({
  id: '/franchise/$slug',
  path: '/franchise/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DecadeSlugRoute = DecadeSlugRouteImport.update({
  id: '/decade/$slug',
  path: '/decade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamReturnRoute = AuthSteamReturnRouteImport.update({
  id: '/auth/steam/return',
  path: '/auth/steam/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamLoginRoute = AuthSteamLoginRouteImport.update({
  id: '/auth/steam/login',
  path: '/auth/steam/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/retro': typeof RetroRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/decade/$slug': typeof DecadeSlugRoute
  '/franchise/$slug': typeof FranchiseSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/lists/': typeof ListsIndexRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
  '/auth/steam/return': typeof AuthSteamReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/retro': typeof RetroRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/decade/$slug': typeof DecadeSlugRoute
  '/franchise/$slug': typeof FranchiseSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/lists': typeof ListsIndexRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
  '/auth/steam/return': typeof AuthSteamReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/retro': typeof RetroRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/decade/$slug': typeof DecadeSlugRoute
  '/franchise/$slug': typeof FranchiseSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/lists/': typeof ListsIndexRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
  '/auth/steam/return': typeof AuthSteamReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/feed'
    | '/login'
    | '/profile'
    | '/retro'
    | '/search'
    | '/categories/$slug'
    | '/decade/$slug'
    | '/franchise/$slug'
    | '/games/$id'
    | '/lists/$id'
    | '/u/$username'
    | '/lists/'
    | '/auth/steam/login'
    | '/auth/steam/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/feed'
    | '/login'
    | '/profile'
    | '/retro'
    | '/search'
    | '/categories/$slug'
    | '/decade/$slug'
    | '/franchise/$slug'
    | '/games/$id'
    | '/lists/$id'
    | '/u/$username'
    | '/lists'
    | '/auth/steam/login'
    | '/auth/steam/return'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/feed'
    | '/login'
    | '/profile'
    | '/retro'
    | '/search'
    | '/categories/$slug'
    | '/decade/$slug'
    | '/franchise/$slug'
    | '/games/$id'
    | '/lists/$id'
    | '/u/$username'
    | '/lists/'
    | '/auth/steam/login'
    | '/auth/steam/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RetroRoute: typeof RetroRoute
  SearchRoute: typeof SearchRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DecadeSlugRoute: typeof DecadeSlugRoute
  FranchiseSlugRoute: typeof FranchiseSlugRoute
  GamesIdRoute: typeof GamesIdRoute
  ListsIdRoute: typeof ListsIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ListsIndexRoute: typeof ListsIndexRoute
  AuthSteamLoginRoute: typeof AuthSteamLoginRoute
  AuthSteamReturnRoute: typeof AuthSteamReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retro': {
      id: '/retro'
      path: '/retro'
      fullPath: '/retro'
      preLoaderRoute: typeof RetroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise/$slug': {
      id: '/franchise/$slug'
      path: '/franchise/$slug'
      fullPath: '/franchise/$slug'
      preLoaderRoute: typeof FranchiseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decade/$slug': {
      id: '/decade/$slug'
      path: '/decade/$slug'
      fullPath: '/decade/$slug'
      preLoaderRoute: typeof DecadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/return': {
      id: '/auth/steam/return'
      path: '/auth/steam/return'
      fullPath: '/auth/steam/return'
      preLoaderRoute: typeof AuthSteamReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/login': {
      id: '/auth/steam/login'
      path: '/auth/steam/login'
      fullPath: '/auth/steam/login'
      preLoaderRoute: typeof AuthSteamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RetroRoute: RetroRoute,
  SearchRoute: SearchRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DecadeSlugRoute: DecadeSlugRoute,
  FranchiseSlugRoute: FranchiseSlugRoute,
  GamesIdRoute: GamesIdRoute,
  ListsIdRoute: ListsIdRoute,
  UUsernameRoute: UUsernameRoute,
  ListsIndexRoute: ListsIndexRoute,
  AuthSteamLoginRoute: AuthSteamLoginRoute,
  AuthSteamReturnRoute: AuthSteamReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
